
<?php echo $this->tag->form("transaction/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("transaction", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create transaction</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="student_id">Student</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("student_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="librarian_id">Librarian</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("librarian_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="book_id">Book</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("book_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="action">Action</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("action", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="time">Time</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("time", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
