<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("transaction/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("transaction/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Student</th>
            <th>Librarian</th>
            <th>Book</th>
            <th>Action</th>
            <th>Time</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $transaction) { ?>
        <tr>
            <td><?php echo $transaction->id ?></td>
            <td><?php echo $transaction->student_id ?></td>
            <td><?php echo $transaction->librarian_id ?></td>
            <td><?php echo $transaction->book_id ?></td>
            <td><?php echo $transaction->action ?></td>
            <td><?php echo $transaction->time ?></td>
            <td><?php echo $this->tag->linkTo(array("transaction/edit/" . $transaction->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("transaction/delete/" . $transaction->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("transaction/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("transaction/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("transaction/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("transaction/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
