<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("librarian/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("librarian/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>First Of Name</th>
            <th>Last Of Name</th>
            <th>Email</th>
            <th>User Of Name</th>
            <th>Password</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $librarian) { ?>
        <tr>
            <td><?php echo $librarian->id ?></td>
            <td><?php echo $librarian->first_name ?></td>
            <td><?php echo $librarian->last_name ?></td>
            <td><?php echo $librarian->email ?></td>
            <td><?php echo $librarian->user_name ?></td>
            <td><?php echo $librarian->password ?></td>
            <td><?php echo $this->tag->linkTo(array("librarian/edit/" . $librarian->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("librarian/delete/" . $librarian->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("librarian/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("librarian/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("librarian/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("librarian/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
