
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("book/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("book", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit book</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ISBN">ISBN</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ISBN", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">Author</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="short_description">Short Of Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("short_description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="page_number">Page Of Number</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("page_number", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="publisher">Publisher</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("publisher", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
